# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# Site settings
title:
  en: v8areu personal blog!
  id: Blog pribadi v8areu!
description:
  en: My awesome website! yay! It contains bashing, mumbling, grumbling, about techno world which I've been really-really interested on. This is a personal blog of Muhamad Fakhrusy.
  id: Seluruh curhatan, tangisan, dan momen bersama teknologi komputer. Ini adalah blog pribadi Muhamad Fakhrusy.
index:
  en:
  id: index-id.html
feed:
  en: /feed.xml
  id: /feed-id.xml
crf:
  en: Copyright v8areu 2016. 
  id: Copyright v8areu pada tahun 2016. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://v8areu.github.io" # the base hostname & protocol for your site
        
# Sosmed and user info
owner:
  name:         Muhamad Fakhrusy
  email:        mfakhrusy@live.com
  twitter:      v8areu
  github:       v8areu
  facebook:     v8areu

# Build settings
timezone:     Asia/Jakarta
markdown:     kramdown

